### ISSUE TITLE
Settling accomodation/ferry accounts.

### ISSUE THREAD

**Issue by grd349** [grd349/CycleTrip#12]
I'm putting this on here to remind me to do this.  I'll wait a few days for all the charges to hit my account so that I know what I actually paid and then I'll tally up who owes me what.

All the hotels are booked - the ferry is booked - the Eurostars are booked.  It looks lie we are doing this.

**Comment by grd349** [comment]
What I have spent so far with liabilities listed as (ben/guy/jimmy/paul).

Guildford Hotel £137 (g/p) - (p £68.5)
Ferry inc cabin £144 (g/j/p) - (j&p £42)
Dieppe Hotel £219.34 (b/g/j/p) - (b/j/p £55)
Beauvais Hotel £Not yet paid but will be EUR180.
Chantilly Hotel £191.29 (b/g/j/p) - (b/j/p £48)

So - if I total these up I have ...

- [x] Paul £213.50
- [x] Jimmy £145.00
- [x] Ben £103.00

Please check my maths and shout if you think I have something wrong - it's entirely possible.  Here are my account details, please transfer when you are ready!  (I'll WA you the bank details).

**Comment by pxr329** [comment]
For the ferry shouldn't Jimmy and I be paying £48 each? If it's split equally 3 ways, or is there a reason your paying £60 for that one?

**Comment by grd349** [comment]
> For the ferry shouldn't Jimmy and I be paying £48 each? If it's split equally 3 ways, or is there a reason your paying £60 for that one?

I have got the Commodore Suite (Mother F**king VIP) and you guys have just a normal cabin. :)

**Comment by grd349** [comment]
Just jimmy left on this one.  Thanks Paul and Ben.

**Comment by JHepto** [comment]
All paid
