### ISSUE TITLE
Make a list of essential and worth it items.

### ISSUE THREAD

**Issue by grd349** [grd349/CycleTrip#13]
When I get a second I'll make list of kit etc we need and what we probably want.  If we are clever, only one of use will bring chain oil, perhaps sun cream, etc etc.  

Feel free to add things here that need to go on this list.  Once I have made the list you should be able to add directly on github in the list.

Passports (not Ben) - Bike locks - Spare inner tubes (probably minimum 2, ideally 3) - multitool - tyre levers - evening wear - chamois cream (lots of this) - chargers for Garmins & phones etc - plug adapters (not Ben) - first aid kit - chain oil - bike pump - water bottles - sun cream - ...

**Comment by pxr329** [comment]
Having not done a multiday trip like this before I'm going on guess work for much of it, but I assume some basics in addition to the above will be necassary, such as bathroom kit (toothbrush, etc), riding cloths?

Also there are a few items I keep in my saddle bag on most rides, in addition to the ones you've already listed, spoke tool - valve core tool - chain tool - spare master link - zip ties - spare lights. I was also considering bringing one spare tyre in case the terrain gets a bit rough and chews through my tyres quicker than expected (is this OTT?).

Also I guess we'll know nearer the time, but in the same thought as sun cream, we might need wet weather gear?

**Comment by pxr329** [comment]
While I think of it, how many water bottles did you and Ben take with you last time? Was it enough?

**Comment by grd349** [comment]
Sorry for the delay ... 1 bottle was fine for Ben.  I needed 2 but I also refilled and purchased fizzy drinks as and when I could.  

There are plenty of 'get out of jail' places along the way where things can be purchased.  Most of our overnights are in sizeable towns so I wouldn't panic too much.  We'll figure it all out! :)

**Comment by grd349** [comment]
Closing now that I have packed.  Not to self for future - this actually helped as I nearly forgot my plug adaptor :)
