### ISSUE TITLE
Book ferry

### ISSUE THREAD

**Issue by grd349** [grd349/CycleTrip#2]
We need to book the ferry.  I will do this.  We need the ferry for Paul, Jimmy, & Guy each with a bicycle.

We need to decide on a cabin:

- No cabin
- One 4 berth cabin @£35
- Three 1 berth cabins @3*£30.  

The ferry date and time is Thursday September 5, 2019 at 17:30.

The operator will be DFDS.  

I need the go ahead from Jimmy and Paul:

- [x] Guy
- [x] Paul
- [x] Jimmy

Tick when you are happy.  Discuss the cabin options below.

**Comment by JHepto** [comment]
How long is the journey? Happy to have a 4 person berth

**Comment by grd349** [comment]
Journey time is 4 hours!

**Comment by pxr329** [comment]
What advantage does having a cabin give? As we won't be sleeping in it. Would we need it to store our bikes for the trip? or are they stored elsewhere?

**Comment by grd349** [comment]
Cabin has a shower if we need to freshen up (gotta fresh'n up).  It's a place to nap.  A place to store bags.  It's not essential though.

The bikes will be stored below decks with the cars and lorries.

**Comment by JHepto** [comment]
Cool, i’ll vote for a four berth cabin 👍🏻

**Comment by pxr329** [comment]
4 Berth is fine with me too, I guess freshening up for the voyage wouldn't be a bad idea. I assume the majority of the resting will be done once we arrive at Dieppe?

**Comment by grd349** [comment]
Dinner on the ferry.  Plus a couple of drinks.

Arrive Dieppe at 23:00 and cycle the short distance to the hotel - it's an adventure so bring lights.

Arrive hotel and sleep like crazy.  Get up and eat all of the breakfast they have ready for a longish day.

**Comment by grd349** [comment]
Okay - I'll book the ferry (probably tomorrow now).  I'll book a 4 berth cabin under my name and add you two as bike passengers, which needs to be done separately.  I confirm here when done.

**Comment by JHepto** [comment]
Cheers buddy

**Comment by grd349** [comment]
Booking #1  : Booking confirmation reference 19336402 (Guy)
Booking #2 : Booking confirmation reference 18147560 (Paul)
Booking #3 : Booking confirmation reference 16954047 (Jimmy)

Ferry is now booked.
