### ISSUE TITLE
Guildford accomodation

### ISSUE THREAD

**Issue by grd349** [grd349/CycleTrip#3]
Paul and Guy need a hotel (bike friendly) in Guildford on Wednesday 4th Sept.  

Paul - we will share a room to keep costs down.  

My suggestion is .. https://www.booking.com/hotel/gb/holiday-inn-guildford.en-gb.html?aid=304142;label=gen173nr-1DCAEoggI46AdIM1gEaFCIAQGYAQm4AQfIAQzYAQPoAQGIAgGoAgO4AprJs-kFwAIB;sid=9ab2660e5fbce9ed4799c7c825bae74c;all_sr_blocks=3410402_95154952_0_1_0;checkin=2019-09-04;checkout=2019-09-05;dest_id=-2597829;dest_type=city;dist=0;group_adults=2;hapos=4;highlighted_blocks=3410402_95154952_0_1_0;hpos=4;nflt=tdb%3D2%3Bmealplan%3D1%3Bht_id%3D204%3B;room1=A%2CA;sb_price_type=total;sr_order=popularity;srepoch=1563223517;srpvid=3efc91ee1f2d0193;type=total;ucfs=1&#hotelTmpl

This includes breakfast.  We should be able to walk into Guildford to get dinner.  There are options nearer the centre but they are closer to £206.

- [x] Need to check hotel would be happy with bikes.
- [x] Paul - you happy with this?

Need to book ASAP because for some reason Guildford is busy on our dates.

**Comment by pxr329** [comment]
Yes I'm happy with that on the condition that it is two single beds and not a double. 
Also how can I check the check box?

**Comment by grd349** [comment]
I assumed you could just click the box - if you can't it's probably a permissions kind of thing.

**Comment by grd349** [comment]
And yes - a twin room.

**Comment by pxr329** [comment]
I can't seem to find any info regarding Holiday Inn and bikes other than some old forum posts ranting about one in Colorado which wouldn't accept them, but others in the US saying they were fine. 

However Premier Inn claim to be bike friendly https://www.premierinn.com/gb/en/why/bike-friendly.html so could be a contingency should Holiday Inn not pan out.

**Comment by grd349** [comment]
Good research!  I'll double check but I think Premier Inn was full in Guildford.  I'll phone Holiday Inn tomorrow as well.

**Comment by grd349** [comment]
I phoned the hotel - they have a luggage room or an office where they can keep two bikes.  We should go ahead and book.

**Comment by pxr329** [comment]
Agreed. I think that'll be fine, should be secure enough if we lock the bikes together at least

**Comment by grd349** [comment]
Booked : Confirmation number | 3235.623.126

I went for the non-refundable rate of £137 inc breakfast in a twin room. 

The hotel has facilities (pool) so bring your trunks!

**Comment by pxr329** [comment]
Brill, thanks.
Cycling shorts double as trunks right?...... :-)
