### ISSUE TITLE
Dieppe accomodation

### ISSUE THREAD

**Issue by grd349** [grd349/CycleTrip#4]
We need a hotel in Dieppe.  The one Kais and I stayed at last time was perfect.  

https://www.booking.com/hotel/fr/hotellapresidence.en-gb.html?aid=304142;label=opensearch-plugin;sid=9ab2660e5fbce9ed4799c7c825bae74c;atlas_src=sr_iw_btn;checkin=2019-09-05;checkout=2019-09-06;dist=0;group_adults=4;group_children=0;highlighted_blocks=22427920_97478403_2_2_0;no_rooms=2;room1=A%2CA;room2=A%2CA;sb_price_type=total;type=total;ucfs=1&

This should be around £56 per person including breakfast in a twin room.  

Signal you contentment in the comments below or suggest an alternative.

- [x] Paul happy
- [x] Jimmy happy
- [x] Ben happy
- [x] Guy happy

The correct date for this hotel is Thursday 5th September arriving around 23:30.

**Comment by pxr329** [comment]
Agreed, sounds good to me. I assume as it's the same place as you two were at last time they are bike friendly?

**Comment by grd349** [comment]
Yes - this one, they put the bikes in a conference room for the night :)

**Comment by grd349** [comment]
Booked: Reservation 2899253563

I've been charged in Euros - I'll check the XR but this should be ~ £211 for both rooms.

Breakfast is included.
