### ISSUE TITLE
Beauvais accomodation

### ISSUE THREAD

**Issue by grd349** [grd349/CycleTrip#5]
This is the same hotel that Ben and I had last time.  

https://www.booking.com/hotel/fr/mercure-beauvais-centre-cathedrale.en-gb.html?label=opensearch-plugin;sid=9ab2660e5fbce9ed4799c7c825bae74c;all_sr_blocks=335827502_124966408_2_2_0%2C335827502_124966408_2_2_0;checkin=2019-09-06;checkout=2019-09-07;dest_id=-1411313;dest_type=city;dist=0;group_adults=4;group_children=0;hapos=16;highlighted_blocks=335827502_124966408_2_2_0%2C335827502_124966408_2_2_0;hpos=16;no_rooms=2;req_adults=4;req_children=0;room1=A%2CA;room2=A%2CA;sb_price_type=total;sr_order=popularity;srepoch=1563225477;srpvid=d5f895c23cc10496;type=total;ucfs=1&#hotelTmpl

Should come in at £41 per person excluding breakfast.  Breakfast is too expensive (£14 per person) so we can find breakfast in Beauvais in the morning.

The correct date for this booking is Friday 6th September.

Who's happy - use the comments below.

- [x] Jimmy
- [x] Ben
- [x] Paul
- [x] Guy

**Comment by pxr329** [comment]
Agreed, sounds good to me. I assume as it's the same place as you two were at last time they are bike friendly?

**Comment by grd349** [comment]
Yes same place as before.  They locked the bikes in some room.  It felt very secure.

**Comment by grd349** [comment]
Booked: Reservation 2214194292

Price is about £161 for both rooms but breakfast is not included.
