### ISSUE TITLE
Chantilly accomodation

### ISSUE THREAD

**Issue by grd349** [grd349/CycleTrip#6]
Chantilly looks to be busy on our day of arrival.  Hence this is a little more expensive

https://www.booking.com/hotel/fr/du-parc-chantilly.en-gb.html?aid=304142;label=opensearch-plugin;sid=9ab2660e5fbce9ed4799c7c825bae74c;atlas_src=sr_iw_btn;checkin=2019-09-07;checkout=2019-09-08;dist=0;group_adults=4;group_children=0;highlighted_blocks=4875512_156186347_4_42_0;no_rooms=2;room1=A%2CA;room2=A%2CA;sb_price_type=total;type=total;ucfs=1&

This should be something like £290 divided by 4 including breakfast.  

- [x] Paul
- [x] Ben
- [x] Jimmy
- [x] Guy

Ticked when happy.

**Comment by grd349** [comment]
I called the hotel - they have underground bike parking that is secure (only accessible by guests of the hotel).  I assume we would be happy with that?

**Comment by pxr329** [comment]
Yeah that sounds fine. I lock my bike in similar situations at home/work so I'm happy with that.

**Comment by grd349** [comment]
Booked: Confirmation number: 2899247125

I got it for ~£197 in the end but it doesn't include breakfast.
