### ISSUE TITLE
Plan detailed route :  Guildford - Newhaven

### ISSUE THREAD

**Issue by grd349** [grd349/CycleTrip#8]
We need to plan the detailed route from Guildford to Newhaven.  For the most part this will follow the downs way.  We need to create a gpx file for the nav and redundancy is preferred if anyone else can nav too.

There is no rush on this.

**Comment by pxr329** [comment]
Following the theme from Stage 1, this one is straight from the hotel then onto the NCN223 as far as it goes, then cut across to the NCN2 and follow that until the ferry port. 

https://ridewithgps.com/routes/30555792

**Comment by grd349** [comment]
On my GPS
