### ISSUE TITLE
Plan detailed route : Dieppe - Beauvais

### ISSUE THREAD

**Issue by grd349** [grd349/CycleTrip#9]
This route should be easy as we are now following the Avenue Verte.  Still, I would like to have it in the nav.

**Comment by pxr329** [comment]
I've followed the Avenue Verte route from the website, the gpx available on the site was Paris to London, so I've just reversed it and tweaked for our specific start/end points. 

https://ridewithgps.com/routes/30611921

**Comment by grd349** [comment]
On my GPS
